//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NUMC.Plugins.KeyboardLayouts {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class KeyboardLayoutResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KeyboardLayoutResource() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NUMC.Plugins.KeyboardLayouts.KeyboardLayoutResource", typeof(KeyboardLayoutResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   lVlrcxNHEPwrV/clVUGB28e9lFeBbQKJIARBSIKoRBGKrRKWXZJcmDjKb49P0vbczVo7m6+g7pvp6Xnc+SadTz+t0v7bm3Se9lWR9dJl2r9Jz6az07N12rd5L/04e78+u/1PW/bS69t/Ur30U9rXxmx66e1P0sHwbPbXOt30thw6RJHZNoWq9J7iaHy5GlxM5o6kPsxRdSmM2lO8Gv/p0KpQgRhysyUoa57Hy04eygQ4zI6jUjyRk8V6unQUVYBB79KoGrluGapsT/BoPJkPL8eTKeKoysM0+Y6lLBjLveRrwgfEdPiM4b9Ifnd4G8hiDy8sg2cOnMux5xUD1wDnItjyxEuAAxbYgzXX3gAcqP0ebHjOORog1AH13jg5t+9olPxDDHLwzr7E8C7ZUM0jiqa4/3vJV46glKXPS+79H4CW5cs9AZ6iawpZ/JLH/jOeHRDfoQ2P/DGerWW04pG/dGgjd5rK6moXemUdfPtbRyEXTmWmYtm/vkS3yukTHiEc[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string KeyBoard {
            get {
                return ResourceManager.GetString("KeyBoard", resourceCulture);
            }
        }
    }
}
