//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NUMC.Language {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        public static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NUMC.Language.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Installed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _107 {
            get {
                return ResourceManager.GetString("107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Online과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _108 {
            get {
                return ResourceManager.GetString("108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _109 {
            get {
                return ResourceManager.GetString("109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   loading plugins information..과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _110 {
            get {
                return ResourceManager.GetString("110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   downloading list..과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _111 {
            get {
                return ResourceManager.GetString("111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to uninstall the plug-in &apos;{0}&apos;?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _112 {
            get {
                return ResourceManager.GetString("112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to install the plug-in &apos;{0}&apos;?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _113 {
            get {
                return ResourceManager.GetString("113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preparing to download...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _114 {
            get {
                return ResourceManager.GetString("114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Downloading... {0]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _115 {
            get {
                return ResourceManager.GetString("115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Changing name...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _116 {
            get {
                return ResourceManager.GetString("116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cleaning up...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _117 {
            get {
                return ResourceManager.GetString("117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Settings: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ApplicationMenu_CurrentSettings {
            get {
                return ResourceManager.GetString("ApplicationMenu_CurrentSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Release all keys과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ApplicationMenu_ReleaseAllKeys {
            get {
                return ResourceManager.GetString("ApplicationMenu_ReleaseAllKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please upload your file here과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FileDropControl_Text {
            get {
                return ResourceManager.GetString("FileDropControl_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the key to use, or
        ///Mouse over here and press the key과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HookingControl_Text {
            get {
                return ResourceManager.GetString("HookingControl_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keys과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string KeysDialog_Title {
            get {
                return ResourceManager.GetString("KeysDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Config과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Main_Title {
            get {
                return ResourceManager.GetString("Main_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Startup program change failed!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Error_ChangeStartProgram_Fail {
            get {
                return ResourceManager.GetString("Message_Error_ChangeStartProgram_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Startup program verification failed!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Error_CheckStartProgram_Fail {
            get {
                return ResourceManager.GetString("Message_Error_CheckStartProgram_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to load settings!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Error_Load_Setting_Fail {
            get {
                return ResourceManager.GetString("Message_Error_Load_Setting_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}
        ///Plugin with exception: {1}
        ///Exception full message:
        ///{2}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Error_Plugin_Exception {
            get {
                return ResourceManager.GetString("Message_Error_Plugin_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to save settings!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Error_Save_Setting_Fail {
            get {
                return ResourceManager.GetString("Message_Error_Save_Setting_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to reset the settings?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Warning_Reset_Setting {
            get {
                return ResourceManager.GetString("Message_Warning_Reset_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Plug-in Manager과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PluginManager_Menu_Text {
            get {
                return ResourceManager.GetString("PluginManager_Menu_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Program_Add_Button {
            get {
                return ResourceManager.GetString("Program_Add_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Program_Edit_Button {
            get {
                return ResourceManager.GetString("Program_Edit_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Program_Exit {
            get {
                return ResourceManager.GetString("Program_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Program_File_Button {
            get {
                return ResourceManager.GetString("Program_File_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Info과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Program_Info {
            get {
                return ResourceManager.GetString("Program_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move down과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Program_Movedown {
            get {
                return ResourceManager.GetString("Program_Movedown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move up과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Program_Moveup {
            get {
                return ResourceManager.GetString("Program_Moveup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Program_Open {
            get {
                return ResourceManager.GetString("Program_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Program_Remove_Button {
            get {
                return ResourceManager.GetString("Program_Remove_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Program_Reset_Button {
            get {
                return ResourceManager.GetString("Program_Reset_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Program_Save_Button {
            get {
                return ResourceManager.GetString("Program_Save_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Program과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Program_StartProgram {
            get {
                return ResourceManager.GetString("Program_StartProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Script Editor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ScriptEditor_Menu_Text {
            get {
                return ResourceManager.GetString("ScriptEditor_Menu_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Portable과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Setting_Portable {
            get {
                return ResourceManager.GetString("Setting_Portable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Key Ignore과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string VirtualInput_Menu_KeyIgnore {
            get {
                return ResourceManager.GetString("VirtualInput_Menu_KeyIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Virtual input...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string VirtualInput_Menu_Name {
            get {
                return ResourceManager.GetString("VirtualInput_Menu_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add virtual input과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string VirtualInput_Runtime_Add_Text {
            get {
                return ResourceManager.GetString("VirtualInput_Runtime_Add_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undo|Redo|Enlarge brush|Shrink brush|Zoom in|Zoom out|Brush|Eraser|Paint|Hand|Magnifier|Disabled (ignore key)|Disable과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string VirtualInput_Sample_Menu_Items {
            get {
                return ResourceManager.GetString("VirtualInput_Sample_Menu_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Primary key과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string VirtualInputDialog_SendKeys_Name {
            get {
                return ResourceManager.GetString("VirtualInputDialog_SendKeys_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   String input과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string VirtualInputDialog_TextEntry_Name {
            get {
                return ResourceManager.GetString("VirtualInputDialog_TextEntry_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Virtual input과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string VirtualInputDialog_Title {
            get {
                return ResourceManager.GetString("VirtualInputDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Virtual key과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string VirtualInputDialog_VirtualKey_Name {
            get {
                return ResourceManager.GetString("VirtualInputDialog_VirtualKey_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Virtual simultaneous input과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string VirtualInputDialog_VirtualSendKeys_Name {
            get {
                return ResourceManager.GetString("VirtualInputDialog_VirtualSendKeys_Name", resourceCulture);
            }
        }
    }
}
