//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NUMC.Language {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        public static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NUMC.Language.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   If there is a mouse in the text box, key hooking starts.
        ///Hooking is in progress.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CustomKeyDialog_KeyHook_Tip_Caption {
            get {
                return ResourceManager.GetString("CustomKeyDialog_KeyHook_Tip_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To use hooking...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CustomKeyDialog_KeyHook_Tip_Title {
            get {
                return ResourceManager.GetString("CustomKeyDialog_KeyHook_Tip_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Some special keys cannot be used. (WinKey)
        ///Combines with short text input and simple shortcut designation.
        ///Press and release is not possible.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CustomKeyDialog_SendKeys_Caption {
            get {
                return ResourceManager.GetString("CustomKeyDialog_SendKeys_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Primary key과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CustomKeyDialog_SendKeys_Name {
            get {
                return ResourceManager.GetString("CustomKeyDialog_SendKeys_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Only string input is possible.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CustomKeyDialog_TextEntry_Caption {
            get {
                return ResourceManager.GetString("CustomKeyDialog_TextEntry_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   String input과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CustomKeyDialog_TextEntry_Name {
            get {
                return ResourceManager.GetString("CustomKeyDialog_TextEntry_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Key Setting Wizard과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CustomKeyDialog_Title {
            get {
                return ResourceManager.GetString("CustomKeyDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can control the entire keyboard.
        ///Press and release support.
        ///Suitable for specifying shortcut keys.
        ///Illegal for text input.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CustomKeyDialog_VirtualKey_Caption {
            get {
                return ResourceManager.GetString("CustomKeyDialog_VirtualKey_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Virtual key과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CustomKeyDialog_VirtualKey_Name {
            get {
                return ResourceManager.GetString("CustomKeyDialog_VirtualKey_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Allows full keyboard control.
        ///Suitable for single shortcuts that do not use press and release.
        ///Press and release is not possible.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CustomKeyDialog_VirtualSendKeys_Caption {
            get {
                return ResourceManager.GetString("CustomKeyDialog_VirtualSendKeys_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Virtual simultaneous input과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CustomKeyDialog_VirtualSendKeys_Name {
            get {
                return ResourceManager.GetString("CustomKeyDialog_VirtualSendKeys_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Delay Wizard과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DelayAddDialog_Title {
            get {
                return ResourceManager.GetString("DelayAddDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enum Wizard과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EnumDialog_Title {
            get {
                return ResourceManager.GetString("EnumDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Function Wizard과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FunctionAddDialog_Title {
            get {
                return ResourceManager.GetString("FunctionAddDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clean up Code과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string JsonEditorDialog_CleanUp {
            get {
                return ResourceManager.GetString("JsonEditorDialog_CleanUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Editing Mode과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string JsonEditorDialog_EditingMode {
            get {
                return ResourceManager.GetString("JsonEditorDialog_EditingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find Keys Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string JsonEditorDialog_FindKey {
            get {
                return ResourceManager.GetString("JsonEditorDialog_FindKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find Virtual Keys Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string JsonEditorDialog_FindVirtualKey {
            get {
                return ResourceManager.GetString("JsonEditorDialog_FindVirtualKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New CustomKey과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string JsonEditorDialog_NewCustomKey {
            get {
                return ResourceManager.GetString("JsonEditorDialog_NewCustomKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New WhiteListKey과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string JsonEditorDialog_NewWhiteListKey {
            get {
                return ResourceManager.GetString("JsonEditorDialog_NewWhiteListKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save And Apply과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string JsonEditorDialog_SaveAndApply {
            get {
                return ResourceManager.GetString("JsonEditorDialog_SaveAndApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Json Editor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string JsonEditorDialog_Title {
            get {
                return ResourceManager.GetString("JsonEditorDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the key to use, or
        ///Mouse over here and press the key과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string KeyAddDialog_TipLabel {
            get {
                return ResourceManager.GetString("KeyAddDialog_TipLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Key Wizard과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string KeyAddDialog_Title {
            get {
                return ResourceManager.GetString("KeyAddDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add delay과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MacroSettingDialog_AddDelay {
            get {
                return ResourceManager.GetString("MacroSettingDialog_AddDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Function과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MacroSettingDialog_AddFunction {
            get {
                return ResourceManager.GetString("MacroSettingDialog_AddFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Keystroke과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MacroSettingDialog_AddKeystroke {
            get {
                return ResourceManager.GetString("MacroSettingDialog_AddKeystroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Text Input과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MacroSettingDialog_AddTextInput {
            get {
                return ResourceManager.GetString("MacroSettingDialog_AddTextInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delay과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MacroSettingDialog_Delay {
            get {
                return ResourceManager.GetString("MacroSettingDialog_Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Function과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MacroSettingDialog_Function {
            get {
                return ResourceManager.GetString("MacroSettingDialog_Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Go to Function과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MacroSettingDialog_GotoFunction {
            get {
                return ResourceManager.GetString("MacroSettingDialog_GotoFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Key Click과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MacroSettingDialog_KeyClick {
            get {
                return ResourceManager.GetString("MacroSettingDialog_KeyClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Key down과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MacroSettingDialog_Keydown {
            get {
                return ResourceManager.GetString("MacroSettingDialog_Keydown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Key up과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MacroSettingDialog_Keyup {
            get {
                return ResourceManager.GetString("MacroSettingDialog_Keyup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Release all keys과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MacroSettingDialog_KeyUpAll {
            get {
                return ResourceManager.GetString("MacroSettingDialog_KeyUpAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MacroSettingDialog_LoadSetting {
            get {
                return ResourceManager.GetString("MacroSettingDialog_LoadSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modules...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MacroSettingDialog_Modules {
            get {
                return ResourceManager.GetString("MacroSettingDialog_Modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Event removal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MacroSettingDialog_Remove {
            get {
                return ResourceManager.GetString("MacroSettingDialog_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove all events과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MacroSettingDialog_RemoveAll {
            get {
                return ResourceManager.GetString("MacroSettingDialog_RemoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Execution과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MacroSettingDialog_RunFile {
            get {
                return ResourceManager.GetString("MacroSettingDialog_RunFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text Input과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MacroSettingDialog_TextInput {
            get {
                return ResourceManager.GetString("MacroSettingDialog_TextInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Macro Setting Wizard과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MacroSettingDialog_Title {
            get {
                return ResourceManager.GetString("MacroSettingDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Custom key...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_CustomKey {
            get {
                return ResourceManager.GetString("Main_CustomKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Json Editor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_JsonEditor {
            get {
                return ResourceManager.GetString("Main_JsonEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Key Ignore과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_KeyIgnore {
            get {
                return ResourceManager.GetString("Main_KeyIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Macro...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_Macro {
            get {
                return ResourceManager.GetString("Main_Macro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Program과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_StartProgram {
            get {
                return ResourceManager.GetString("Main_StartProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_Title {
            get {
                return ResourceManager.GetString("Main_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Startup program change failed!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Message_Error_ChangeStartProgram_Fail {
            get {
                return ResourceManager.GetString("Message_Error_ChangeStartProgram_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Startup program verification failed!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Message_Error_CheckStartProgram_Fail {
            get {
                return ResourceManager.GetString("Message_Error_CheckStartProgram_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to load settings!
        ///Do you want to initialize settings?
        ///
        ///Message:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Message_Error_LoadSetting_Fail {
            get {
                return ResourceManager.GetString("Message_Error_LoadSetting_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to save this setting?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Message_Information_SaveThisSetting {
            get {
                return ResourceManager.GetString("Message_Information_SaveThisSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Would you like to use this setting?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Message_Information_ThisSetting {
            get {
                return ResourceManager.GetString("Message_Information_ThisSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit mode is active!
        ///Editing the settings can cause the program to become unstable!
        ///Would you like to continue?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Message_Warning_Editing {
            get {
                return ResourceManager.GetString("Message_Warning_Editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This menu is for experimentation only!
        ///Using this menu may make the program unsafe!
        ///Do you want to continue?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Message_Warning_Menu {
            get {
                return ResourceManager.GetString("Message_Warning_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exception {1} occurred in module {0}.
        ///{2}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Module_Exception {
            get {
                return ResourceManager.GetString("Module_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Program_Add_Button {
            get {
                return ResourceManager.GetString("Program_Add_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Program_Edit_Button {
            get {
                return ResourceManager.GetString("Program_Edit_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Program_Exit {
            get {
                return ResourceManager.GetString("Program_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Program_File_Button {
            get {
                return ResourceManager.GetString("Program_File_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Info과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Program_Info {
            get {
                return ResourceManager.GetString("Program_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move down과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Program_Movedown {
            get {
                return ResourceManager.GetString("Program_Movedown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move up과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Program_Moveup {
            get {
                return ResourceManager.GetString("Program_Moveup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Program_Open {
            get {
                return ResourceManager.GetString("Program_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Program_Remove_Button {
            get {
                return ResourceManager.GetString("Program_Remove_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Program_Reset_Button {
            get {
                return ResourceManager.GetString("Program_Reset_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Program_Save_Button {
            get {
                return ResourceManager.GetString("Program_Save_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Run File Wizard과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RunFileDialog_Title {
            get {
                return ResourceManager.GetString("RunFileDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undo|Redo|Enlarge brush|Shrink brush|Zoom in|Zoom out|Brush|Eraser|Paint|Hand|Magnifier|Disabled (ignore key)|Disable과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Sample_Menu_Items {
            get {
                return ResourceManager.GetString("Sample_Menu_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drop the file here과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SetSettingDialog_DropLabel {
            get {
                return ResourceManager.GetString("SetSettingDialog_DropLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Settings Change Wizard과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SetSettingDialog_Title {
            get {
                return ResourceManager.GetString("SetSettingDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Portable과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Setting_Portable {
            get {
                return ResourceManager.GetString("Setting_Portable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Text Input Wizard과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TextInputAddDialog_Title {
            get {
                return ResourceManager.GetString("TextInputAddDialog_Title", resourceCulture);
            }
        }
    }
}
